version: '2'
services:
  hrcm:
    image: hrcm
    build:
      context: .
    env_file:
      - ./.env
    links:
      - mongo:mongo
    ports:
      - 5100:5100
    volumes:
      - ./app:/app

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./mongodb/data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
